### ISSUE TITLE
cpu statistics not implemented for: windows ???

### ISSUE THREAD

**Issue by wangchaodeyuzhou** [livekit/ingress#170]
windows run main,go found error!!!
![截图20231122193628](https://github.com/livekit/ingress/assets/48428618/09909081-8631-45b2-b20f-e0176b62ddb5)

**Comment by wangchaodeyuzhou** [comment]
cana add config disable cpu statistics in config.yaml ?

**Comment by biglittlebigben** [comment]
There should be a workaround in https://github.com/livekit/ingress/pull/220/commits/1e90f98c96f712e7aabccb2149d170ec187a6b7b. Ingress should run on Windows, but with no capacity enforcement.
