### ISSUE TITLE
exec: "ingress": executable file not found in %PATH% ?

### ISSUE THREAD

**Issue by wangchaodeyuzhou** [livekit/ingress#171]
I found cmd.Err have exec: "ingress": executable file not found in %PATH% ?
![image](https://github.com/livekit/ingress/assets/48428618/36807308-2e2c-499c-9b92-116cac4a8504)
this is my ingress log

> `2023-11-24T18:34:58.019+0800    INFO    ingress redis/redis.go:127      connecting to redis                                                                                                            {
"nodeID": "NE_BJf5hZKdUSCN", "simple": true, "addr": "localhost:6379"}
time="2023-11-24T18:47:18+08:00" level=info msg="Change state: From = <Unknown>, To = NotConnected(Server)" logger=ingress nodeID=NE_BJf5hZKdUSCN state="NotConnected(Server)" stream_id=0
time="2023-11-24T18:47:18+08:00" level=info msg=Connect logger=ingress nodeID=NE_BJf5hZKdUSCN state="NotConnected(Server)" stream_id=0
time="2023-11-24T18:47:18+08:00" level=info msg="Set win ack size: Size = 2147483647" logger=ingress nodeID=NE_BJf5hZKdUSCN state="NotConnected(Server)" stream_id=0
time="2023-11-24T18:47:18+08:00" level=info msg="Set peer bandwidth: Size = 786432, Limit = 0" logger=ingress nodeID=NE_BJf5hZKdUSCN state="NotConnected(Server)" stream_id=0
time="2023-11-24T18:47:18+08:00" level=info msg="Stream Begin: ID = 0" logger=ingress nodeID=NE_BJf5hZKdUSCN state="NotConnected(Server)" stream_id=0
time="2023-11-24T18:47:18+08:00" level=info msg="Connect: ResponseBody = &message.NetConnectionConnectResult{Properties:message.NetConnectionConnectResultProperties{FMSVer:\"GO-RTMP/0,0,0,0\", Capabil
ities:31, Mode:1}, Information:message.NetConnectionConnectResultInformation{Level:\"status\", Code:\"NetConnection.Connect.Success\", Description:\"Connection succeeded.\", Data:amf0.ECMAArray{\"type
\":\"go-rtmp\", \"version\":\"master\"}}}" logger=ingress nodeID=NE_BJf5hZKdUSCN state="NotConnected(Server)" stream_id=0
time="2023-11-24T18:47:18+08:00" level=info msg=Connected logger=ingress nodeID=NE_BJf5hZKdUSCN state="NotConnected(Server)" stream_id=0
time="2023-11-24T18:47:18+08:00" level=info msg="Change state: From = NotConnected(Server), To = Connected(Server)" logger=ingress nodeID=NE_BJf5hZKdUSCN state="Connected(Server)" stream_id=0
time="2023-11-24T18:47:18+08:00" level=info msg="Release stream...: StreamName = GnrxqezSrVnf" logger=ingress nodeID=NE_BJf5hZKdUSCN state="Connected(Server)" stream_id=0
time="2023-11-24T18:47:18+08:00" level=info msg="FCPublish stream...: StreamName = GnrxqezSrVnf" logger=ingress nodeID=NE_BJf5hZKdUSCN state="Connected(Server)" stream_id=0
time="2023-11-24T18:47:18+08:00" level=info msg="Stream creating...: &message.NetConnectionCreateStream{}" logger=ingress nodeID=NE_BJf5hZKdUSCN state="Connected(Server)" stream_id=0
time="2023-11-24T18:47:18+08:00" level=info msg="Change state: From = <Unknown>, To = Inactive(Server)" logger=ingress nodeID=NE_BJf5hZKdUSCN state="Inactive(Server)" stream_id=1
time="2023-11-24T18:47:18+08:00" level=info msg="Stream created...: NewStreamID = 1" logger=ingress nodeID=NE_BJf5hZKdUSCN state="Connected(Server)" stream_id=0
time="2023-11-24T18:47:18+08:00" level=info msg="Publisher is comming: &message.NetStreamPublish{CommandObject:interface {}(nil), PublishingName:\"GnrxqezSrVnf\", PublishingType:\"live\"}" logger=ingr
ess nodeID=NE_BJf5hZKdUSCN state="Inactive(Server)" stream_id=1
2023-11-24T18:47:18.216+0800    INFO    ingress service/service.go:382  received ingress info                                                                                                          {
"nodeID": "NE_BJf5hZKdUSCN", "ingressID": "IN_TJHKcQP8Ygh2", "streamKey": "GnrxqezSrVnf", "resourceID": "RT_nowW8MRPzN7E", "ingressInfo": "ingress_id:\"IN_TJHKcQP8Ygh2\" name:\"test-ingress\" stream_k
ey:\"{Gnr...Vnf}\" url:\"rtmp://localhost:1935/live\" audio:{} video:{} room_name:\"7bzo-wkka\" participant_identity:\"kkkk\" participant_name:\"kkkk\" reusable:true state:{status:ENDPOINT_BUFFERING s
tarted_at:1700822838208197100 resource_id:\"RT_nowW8MRPzN7E\"}"}
2023-11-24T18:47:18.242+0800    INFO    ingress service/session_manager.go:47  ingress started                                                                                                         {
"nodeID": "NE_BJf5hZKdUSCN", "ingressID": "IN_TJHKcQP8Ygh2", "resourceID": "RT_nowW8MRPzN7E"}
2023-11-24T18:47:23.989+0800    INFO    ingress rtmp/server.go:206      Received a new published stream                                                                                                {
"nodeID": "NE_BJf5hZKdUSCN", "streamKey": "GnrxqezSrVnf", "resourceID": "RT_nowW8MRPzN7E"}
2023-11-24T18:47:23.989+0800    ERROR   ingress service/process_manager.go:164 could not launch handler                                                                                                {
"nodeID": "NE_BJf5hZKdUSCN", "error": "exec: \"ingress\": executable file not found in %PATH%"}
github.com/livekit/ingress/pkg/service.(*ProcessManager).awaitCleanup
        D:/直播流媒体/backend/ingress/pkg/service/process_manager.go:164
2023-11-24T18:47:23.990+0800    WARN    ingress service/service.go:401  ingress failed                                                                                                                 {
"nodeID": "NE_BJf5hZKdUSCN", "error": "exec: \"ingress\": executable file not found in %PATH%"}
time="2023-11-24T18:47:23+08:00" level=info msg="Publisher accepted" logger=ingress nodeID=NE_BJf5hZKdUSCN state="Inactive(Server)" stream_id=1
time="2023-11-24T18:47:23+08:00" level=info msg="Change state: From = Inactive(Server), To = Publish(Server)" logger=ingress nodeID=NE_BJf5hZKdUSCN state="Publish(Server)" stream_id=1
2023-11-24T18:47:23.991+0800    INFO    ingress rtmp/server.go:307      key frame found                                                                                                                {
"nodeID": "NE_BJf5hZKdUSCN", "streamKey": "GnrxqezSrVnf", "resourceID": "RT_nowW8MRPzN7E"}
2023-11-24T18:47:23.992+0800    INFO    ingress service/service.go:326  shutting down                                                                                                                  {
"nodeID": "NE_BJf5hZKdUSCN"}
2023-11-24T18:47:23.992+0800    INFO    ingress service/session_manager.go:61  ingress ended                                                                                                           {
"nodeID": "NE_BJf5hZKdUSCN", "ingressID": "IN_TJHKcQP8Ygh2", "resourceID": "RT_nowW8MRPzN7E"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1573fae]

goroutine 65 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).Unregister.func1()
        C:/Users/Administrator/go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/registry.go:372 +0x2e
created by github.com/prometheus/client_golang/prometheus.(*Registry).Unregister in goroutine 1
        C:/Users/Administrator/go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/registry.go:371 +0x198

Debugger finished with the exit code 0
`

**Comment by davidzhao** [comment]
ensure that your $PATH includes Ingress.

**Comment by wangchaodeyuzhou** [comment]
yes, i had add $path, but the problem still exists
![image](https://github.com/livekit/ingress/assets/48428618/a6514b3f-912a-4135-b1f0-0e118705ef53)
![image](https://github.com/livekit/ingress/assets/48428618/c5d28a60-7260-44c5-a171-26f2faca30b8)

**Comment by davidzhao** [comment]
I guess this could be a windows thing. I'm unsure how this works within Windows.

**Comment by wangchaodeyuzhou** [comment]
ok. i try it on linux
